import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DefaultSidebar from "../components/organisms/DefaultSidebar";
import ChatSidebarHeader from "@/components/organisms/ChatSidebarHeader";
import ChatSidebarList from "@/components/organisms/ChatSidebarList";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex">
          <DefaultSidebar />
          <div className="w-sm border-r border-white/10">
            <ChatSidebarHeader />
            <ChatSidebarList />
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
